### ISSUE TITLE
having trouble in getting the active item

### ISSUE THREAD

**Issue by addington-harry** [lmgonzalves/momentum-slider#1]
thanks for this cool plugin.
I'm having a little trouble with getting the right active item index. it's happening when I have the loop enabled.
made a demo here https://codepen.io/Harry-Addington/pen/mYzMvg

try to have a long dragging. or remove the multiplier and drag fast.

and is it possible to have a callback like onDrag, onUpdate or something like these?

any help with this is appreciated

**Comment by lmgonzalves** [comment]
The `change` function is called with the arguments `newIndex` and `oldIndex`, so you don't have to get it like:

```javascript
const { currentIndex } = ms;
```

If you want the corresponding `Node`, then you also need to sum the extra elements that adds the `loop`:

```javascript
// The loop adds 2 extra elements, so the right index is `newIndex + 2`
const index = newIndex + 2;
```

I've update the demo:
https://codepen.io/lmgonzalves/pen/vwVQxg

This is good to get the current index or element, but for transitions, I recommend using the options `style` or [`customStyles`](https://github.com/lmgonzalves/momentum-slider/blob/545e86b49ed5b258266fbe11b8950b59c3cc6245/js/momentum-slider.js#L165) (sorry, no documentation).

At the moment, I don't have time to implement more features, but Pull Request are very welcome :)

**Comment by addington-harry** [comment]
sweet! this is actually what I'm looking for.
there's a tiny issue tho. it's happening when going from the last item to the first. it's like deactivating all elements.
but I'm sure I'll find a way to solve this basically by getting the old and new index.

thanks for your help and for this cool plugin.
