### ISSUE TITLE
Use already existing markup instead of rendering it with JS

### ISSUE THREAD

**Issue by dziku86** [lmgonzalves/momentum-slider#13]
@lmgonzalves could you help me to rewrite momentum-slider so that it will use preexisting html markup instead of rendering it with JS? Or give me some tips on how to do this. I'm still new to programming and this is way too much for my skills.

**Comment by lmgonzalves** [comment]
You can do it already, and only have to provide an HTML structure like this:

```html
<div class="container">
    <!-- Slider container -->
    <div class="ms-container ms-container--horizontal">
        <!-- Slider track -->
        <ul class="ms-track">
            <!-- Slider slides -->
            <li class="ms-slide">1</li>
            <li class="ms-slide">2</li>
            <li class="ms-slide">3</li>
            <li class="ms-slide">4</li>
            <li class="ms-slide">5</li>
        </ul>
    </div>
</div>
```

Please learn more about the library here:
https://scotch.io/tutorials/building-a-fancy-countdown-timer-with-momentumsliderjs#toc-introducing-momentumslider

**Comment by dziku86** [comment]
Thank you! I got it to work.

**Comment by dziku86** [comment]
There is no issue so I am closing it.
