### ISSUE TITLE
Scrolling slider on X axis doesn't prevent page from scrolling on Y axis. 

### ISSUE THREAD

**Issue by dziku86** [lmgonzalves/momentum-slider#4]
### When I'm scrolling MS horizontally page scrolls vertically with it and when I'm scrolling page vertically and stumble upon slider the slider scrolls horizontally. 
This leads to performance issues and bad UX experience. Is there a way to prevent this behavior on mobile devices? All my `eventListeners` are passive so I can't use `prevent.default.` I'm experimenting with `touch-action` but I'm new to coding and make almost everything through trial and error.
Here is a sample video : [https://youtu.be/Grr7t1Kt-qA](https://youtu.be/Grr7t1Kt-qA)

**Comment by lmgonzalves** [comment]
Sorry, but I can't understand the issue very well.
Can you make a reproducible demo on [codepen](https://codepen.io/) or [jsfiddle](http://jsfiddle.net), so I can take a better look?

**Comment by dziku86** [comment]
Here's the demo: [jsfiddle](https://jsfiddle.net/sey29pf3/2/).
Please view it on a mobile device.
When you scrolling down the page and put a finger over the slider, the slider scrolls vertically while the page scrolls down further. I want to disable the slider from scrolling left/right while you scroll the page down just like in the [swiperjs](https://swiperjs.com/demos/).

**Comment by lmgonzalves** [comment]
I can understand the issue now, and I think it is a valid issue.
So, I've done some work to fix it.
Can you try the latest version, and let me know if it works properly now?
Thanks!

**Comment by dziku86** [comment]
Thank you so much! This works great.
